[package]
name = "cli"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.70"
geo = "0.24.1"
geojson = { version = "0.24.0", features = ["geo-types"] }
overline = { path = "../overline" }
rayon = "1.7.0"
