[package]
name = "overline"
version = "0.1.0"
edition = "2021"

[dependencies]
geo = "0.24.1"
geojson = { version = "0.24.0", features = ["geo-types"] }
ordered-float = "3.6.0"
rayon = "1.7.0"
serde = { version = "1.0.159", features = ["derive"] }
